name: Train Pipeline Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # daily at 00:00 UTC
  push:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    env:
      AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      HOPSWORKS_HOST: ${{ secrets.HOPSWORKS_HOST }}
      HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      HOPSWORKS_FEATURE_GROUP: ${{ secrets.HOPSWORKS_FEATURE_GROUP }}
      CITY: Islamabad
      LAT: "33.6844"
      LON: "73.0479"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python -c "print('Starting training...')"
          python -m src.train
