<<<<<<< HEAD
name: Train Pipeline Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # daily 00:00 UTC
  push:
    branches: ["main"]
    paths:
      - "src/train_models.py"
      - ".github/workflows/train_daily.yml"
      - "requirements.txt"

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        env:
          AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          HOPSWORKS_HOST: ${{ secrets.HOPSWORKS_HOST }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

          CITY: Islamabad
          FEATURE_GROUP_NAME: aqi_features_v2
          FEATURE_GROUP_VERSION: "1"
        run: |
          python -c "print('Starting training...')"
          python src/train_models.py
=======
name: Train Pipeline Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        env:
          AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          HOPSWORKS_HOST: ${{ secrets.HOPSWORKS_HOST }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

          CITY: Islamabad
          FEATURE_GROUP_NAME: aqi_features_v2
          FEATURE_GROUP_VERSION: "1"
        run: |
          python -c "print('Starting training...')"
          python src/train_models.py
>>>>>>> 0d62c94ac42e1e6fb1bd5ecb4a23e2c12de2e6bb
